# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locationpost.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='locationpost.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12locationpost.proto\"y\n\x13LocationPostMessage\x12\x13\n\x0blocation_id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t2K\n\x13LocationPostService\x12\x34\n\x06\x43reate\x12\x14.LocationPostMessage\x1a\x14.LocationPostMessageb\x06proto3'
)




_LOCATIONPOSTMESSAGE = _descriptor.Descriptor(
  name='LocationPostMessage',
  full_name='LocationPostMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_id', full_name='LocationPostMessage.location_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person_id', full_name='LocationPostMessage.person_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='LocationPostMessage.longitude', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='LocationPostMessage.latitude', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='LocationPostMessage.creation_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['LocationPostMessage'] = _LOCATIONPOSTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationPostMessage = _reflection.GeneratedProtocolMessageType('LocationPostMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONPOSTMESSAGE,
  '__module__' : 'locationpost_pb2'
  # @@protoc_insertion_point(class_scope:LocationPostMessage)
  })
_sym_db.RegisterMessage(LocationPostMessage)



_LOCATIONPOSTSERVICE = _descriptor.ServiceDescriptor(
  name='LocationPostService',
  full_name='LocationPostService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='LocationPostService.Create',
    index=0,
    containing_service=None,
    input_type=_LOCATIONPOSTMESSAGE,
    output_type=_LOCATIONPOSTMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATIONPOSTSERVICE)

DESCRIPTOR.services_by_name['LocationPostService'] = _LOCATIONPOSTSERVICE

# @@protoc_insertion_point(module_scope)
